server:
  port: 8080
  servlet:
    context-path: /wallparper

aliyun:
  oss:
    # oss对外服务的访问域名
    endpoint: oss-cn-hangzhou.aliyuncs.com
    # 访问身份验证中用到用户标识
    accessKeyId: LTAI5t7GtadpTYenZdzUyWBU
    # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    accessKeySecret: VsmW14Py0engBcJmbhA7Lu7sO8ZsXJ
    # oss的存储空间
    bucketName: wallpaperss
    # 上传文件大小(M)
    maxSize: 100
    # 上传文件夹路径前缀
    dir:
      prefix: images/

spring:
  application:
    name: admin
  cloud:
    nacos:
      server-addr: 112.74.125.228:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://112.74.125.228:3306/wallpaper?serverTimezone=Asia/Shanghai&connectTimeout=10000
    username: root
    password: 910302
    druid:
    minIdle: 50
    time-between-eviction-runs-millis: 60000
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    removeAbandoned: true
    remove-abandoned-timeout: 18000
    web-stat-filter.enabled: true

  redis:
    host: 112.74.125.228
    port: 6379
    jedis:
      pool:
        min-idle: 5
        max-idle: 10
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.wallpaperadmin.entity

logging:
  level:
    com.dscm.wechat.mapper: debug
    com.dscm.wechat.controller: debug
